/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muh;

import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Merve
 */
public class idealGazYasasi extends javax.swing.JFrame {

    /**
     * Creates new form enerji
     */
    public idealGazYasasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        kinetiklEnerji = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        basıncEnerjisi = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("İdeal Gaz Yasası");

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("İdeal Yasasına Göre;");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 180, 230, 22);

        kinetiklEnerji.setBackground(new java.awt.Color(153, 0, 51));
        kinetiklEnerji.setText("Mol Sayısı");
        kinetiklEnerji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kinetiklEnerjiActionPerformed(evt);
            }
        });
        jPanel1.add(kinetiklEnerji);
        kinetiklEnerji.setBounds(310, 10, 110, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muh/images/aaa.png"))); // NOI18N
        jButton3.setText("Grafikte Göster");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(490, 20, 140, 60);

        basıncEnerjisi.setBackground(new java.awt.Color(204, 255, 102));
        basıncEnerjisi.setText("S. Gaz Sabiti");
        basıncEnerjisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basıncEnerjisiActionPerformed(evt);
            }
        });
        jPanel1.add(basıncEnerjisi);
        basıncEnerjisi.setBounds(310, 50, 105, 30);

        jLabel12.setBackground(new java.awt.Color(153, 204, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Spesifik Gaz Sabiti:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 180, 130, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 20, 60, 30);

        jLabel13.setBackground(new java.awt.Color(153, 204, 0));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Basınç Değeri :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 20, 130, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(120, 220, 60, 30);

        jLabel14.setBackground(new java.awt.Color(153, 204, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Hacim Değeri :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 60, 130, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(120, 60, 60, 30);

        jLabel15.setBackground(new java.awt.Color(153, 204, 0));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Sıcaklık Değeri:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 100, 130, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(120, 100, 60, 30);

        jLabel16.setBackground(new java.awt.Color(153, 204, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Molar Kütle   :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 140, 130, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(120, 140, 60, 30);

        jLabel17.setBackground(new java.awt.Color(153, 204, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Mol Sayısı     :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 220, 130, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(120, 180, 60, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(P) ", " " }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(190, 30, 70, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(V)m3", "(V)dm3", "(V)cm3" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(190, 70, 70, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(°K) ", "(°C) ", "(°F)", " " }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(190, 110, 70, 22);

        jButton1.setText("Değerlendir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 270, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 230, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muh/images/giphy.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 70, 490, 320);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muh/images/Adsız.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kinetiklEnerjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kinetiklEnerjiActionPerformed
        kinetikEnerji git = new kinetikEnerji();
        git.show();

    }//GEN-LAST:event_kinetiklEnerjiActionPerformed

    private void basıncEnerjisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basıncEnerjisiActionPerformed

        basincEnerjisi git = new basincEnerjisi();
        git.show();
    }//GEN-LAST:event_basıncEnerjisiActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double p,v,t,mk,r,v2,n;

        //D=Double.parseDouble(jTextField1.getText());
        n=Double.parseDouble(jTextField2.getText());
        v=Double.parseDouble(jTextField3.getText());
        t=Double.parseDouble(jTextField4.getText());
        p=Double.parseDouble(jTextField1.getText());
        mk=Double.parseDouble(jTextField5.getText());
        r=Double.parseDouble(jTextField6.getText());
     
        //A=(Math.PI*(D*D)/1000/4);
        //jLabel5.setText("KESIT ALAN:"+A);


        if((p*v)==(n*r*mk*t))
            jLabel3.setText("uygundur");
        else
            jLabel3.setText("uygun değildir");
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        double p,v,t,mk,r,v2,n;

        //D=Double.parseDouble(jTextField1.getText());
        n=Double.parseDouble(jTextField2.getText());
        v=Double.parseDouble(jTextField3.getText());
        t=Double.parseDouble(jTextField4.getText());
        p=Double.parseDouble(jTextField1.getText());
        mk=Double.parseDouble(jTextField5.getText());
        r=Double.parseDouble(jTextField6.getText());

        DefaultCategoryDataset dcd = new DefaultCategoryDataset();

        dcd.setValue(p,"Önceki Değerler","Basınç(p)");
        dcd.setValue(v,"Önceki Değerler","Hacim(v)");
        dcd.setValue(p*v,"Önceki Değerler","p*v");
        dcd.setValue(n*r*mk*t,"Sonraki Değerler","n*r*mk*t");
        dcd.setValue(n,"Sonraki Değerler","Mol(m)");
        dcd.setValue(r,"Sonraki Değerler","Gaz S.(r)");
        dcd.setValue(mk,"Sonraki Değerler","Molarkütle");
        dcd.setValue(t,"Sonraki Değerler","Sıcaklık");
        

        JFreeChart jchart = ChartFactory.createBarChart3D("p*v = n*r*mk*t","Veriler","Değerler",dcd, PlotOrientation.VERTICAL,true,true,false);

        CategoryPlot plot = jchart.getCategoryPlot();
        plot.setRangeGridlinePaint(Color.black);

        ChartFrame chartFrm = new ChartFrame("Grafiksel Gösterim",jchart,true);
        chartFrm.setVisible(true);
        chartFrm.setSize(500, 400);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(idealGazYasasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(idealGazYasasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(idealGazYasasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(idealGazYasasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new idealGazYasasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basıncEnerjisi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton kinetiklEnerji;
    // End of variables declaration//GEN-END:variables
}
